version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data # Volume for Redis data

  mongodb:
    image: mongo:5.0
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGODB_DB
    volumes:
      - mongo-data:/data/db # Volume for MongoDB data
    ports:
      - '27017:27017'

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    environment:
      MONGODB_HOST: mongodb
      MONGODB_USER: $MONGODB_USER
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      MONGODB_DB: $MONGODB_DB
      JWT_SECRET: $JWT_SECRET
      REFRESH_SECRET: $REFRESH_SECRET
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./src:/app/src # Sync local src folder with container's src folder
      - ./node_modules:/app/node_modules # Avoid re-installing node_modules
    depends_on:
      - mongodb
      - redis
    ports:
      - '3999:3999'
    command: npm run start:dev

volumes:
  mongo-data: # Volume for MongoDB
  redis-data: # Volume for Redis
